spring:
  application:
    name: four-market-api

  output:
    ansi:
      enabled: ALWAYS

app:
  security:
    header-name: "X-Client-Header"
    expected-value: "ABX"


turso:
  url: ${TURSO_DATABASE_URL:}
  authToken: ${TURSO_AUTH_TOKEN:}
  local-path: ${TURSO_LOCAL_PATH:./local.db}

logging:
  level:
    root: info
    in.abx: debug

  pattern:
    console: "%clr(%d{HH:mm:ss}){faint} %clr([%thread]){magenta} %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n"